server:
  port: 8080
  servlet:
    context-path: /test


spring:
  redis:
    host: 192.168.11.1
    password: xtImlMG3Q68iO!KxPvelop@iEAy%dc
    port: 6379
    database: 13
    jedis:
      pool:
        max-active: 8
        min-idle: 3
        max-wait: 10000s
    timeout: 20000s
  datasource:
    username: root
    password: 0XmsxYngfHlesYXM
    url: jdbc:mysql://119.23.65.189:3307/test1?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver


